# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='持仓数量')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='平均成本')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='市值')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='浮动盈亏')),
                ('profit_loss_percent', models.FloatField(default=0, verbose_name='盈亏比例')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_quantity', models.IntegerField(verbose_name='成交数量')),
                ('filled_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='手续费')),
                ('filled_at', models.DateTimeField(auto_now_add=True, verbose_name='成交时间')),
            ],
            options={
                'verbose_name': '成交',
                'verbose_name_plural': '成交',
                'db_table': 'trades',
                'ordering': ['-filled_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', '市价'), ('limit', '限价')], max_length=10, verbose_name='订单类型')),
                ('direction', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='方向')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='限价')),
                ('quantity', models.IntegerField(verbose_name='委托数量')),
                ('status', models.CharField(choices=[('pending', '待成交'), ('partial', '部分成交'), ('filled', '全部成交'), ('cancelled', '已撤销'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('broker_order_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='券商订单ID')),
                ('filled_quantity', models.IntegerField(default=0, verbose_name='已成交数量')),
                ('filled_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交价格')),
                ('filled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='成交金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market_data.stock')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='strategies.strategy')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
