# Generated by Django 6.0.3 on 2026-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('code', models.TextField(verbose_name='策略代码')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=20, verbose_name='语言')),
                ('parameters', models.JSONField(default=dict, verbose_name='策略参数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('stopped', '已停止'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('total_signals', models.PositiveIntegerField(default=0, verbose_name='信号总数')),
                ('win_rate', models.FloatField(default=0, verbose_name='胜率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略',
                'db_table': 'strategies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参数名')),
                ('value', models.CharField(max_length=100, verbose_name='参数值')),
                ('default_value', models.CharField(max_length=100, verbose_name='默认值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '策略参数',
                'verbose_name_plural': '策略参数',
                'db_table': 'strategy_parameters',
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('hold', '持有')], max_length=10, verbose_name='信号类型')),
                ('strength', models.FloatField(default=1.0, verbose_name='信号强度 0-1')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('reason', models.TextField(blank=True, verbose_name='信号原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '策略信号',
                'verbose_name_plural': '策略信号',
                'db_table': 'strategy_signals',
                'ordering': ['-created_at'],
            },
        ),
    ]
