# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyparameter',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='market_data.stock'),
        ),
        migrations.AddField(
            model_name='strategysignal',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='strategies.strategy'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyparameter',
            unique_together={('strategy', 'name')},
        ),
        migrations.AddIndex(
            model_name='strategysignal',
            index=models.Index(fields=['created_at'], name='strategy_si_created_4d909d_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysignal',
            index=models.Index(fields=['strategy', 'created_at'], name='strategy_si_strateg_98b201_idx'),
        ),
    ]
