# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='所属行业')),
                ('market', models.CharField(choices=[('SH', '上海证券交易所'), ('SZ', '深圳证券交易所'), ('BJ', '北京证券交易所')], max_length=2, verbose_name='市场')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否交易')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
                'db_table': 'stocks',
                'indexes': [models.Index(fields=['industry'], name='stocks_industr_72cf08_idx'), models.Index(fields=['market'], name='stocks_market_143d55_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealtimeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价')),
                ('change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='涨跌额')),
                ('change_percent', models.FloatField(verbose_name='涨跌幅')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额')),
                ('open_today', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='今开')),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高')),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低')),
                ('close_yesterday', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='昨收')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_quote', to='market_data.stock')),
            ],
            options={
                'verbose_name': '实时行情',
                'verbose_name_plural': '实时行情',
                'db_table': 'realtime_quotes',
            },
        ),
        migrations.CreateModel(
            name='MinuteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='时间')),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_data', to='market_data.stock')),
            ],
            options={
                'verbose_name': '分钟线数据',
                'verbose_name_plural': '分钟线数据',
                'db_table': 'minute_data',
                'indexes': [models.Index(fields=['datetime'], name='minute_data_datetim_758879_idx'), models.Index(fields=['stock', 'datetime'], name='minute_data_stock_i_a90c3b_idx')],
                'unique_together': {('stock', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='market_data.stock')),
            ],
            options={
                'verbose_name': '日线数据',
                'verbose_name_plural': '日线数据',
                'db_table': 'daily_data',
                'indexes': [models.Index(fields=['date'], name='daily_data_date_81b7e9_idx'), models.Index(fields=['stock', 'date'], name='daily_data_stock_i_8526d6_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
