# Generated by Django 6.0.3 on 2026-03-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
    ]
