# Generated by Django 6.0.3 on 2026-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='初始资金')),
                ('commission', models.FloatField(default=0.0003, verbose_name='手续费率')),
                ('slippage', models.FloatField(default=0.001, verbose_name='滑点')),
                ('final_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最终资金')),
                ('total_return', models.FloatField(blank=True, null=True, verbose_name='总收益率')),
                ('sharpe_ratio', models.FloatField(blank=True, null=True, verbose_name='夏普比率')),
                ('max_drawdown', models.FloatField(blank=True, null=True, verbose_name='最大回撤')),
                ('win_rate', models.FloatField(blank=True, null=True, verbose_name='胜率')),
                ('total_trades', models.PositiveIntegerField(blank=True, null=True, verbose_name='总交易次数')),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '回测',
                'verbose_name_plural': '回测',
                'db_table': 'backtests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总市值')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='现金')),
                ('positions_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='持仓市值')),
                ('daily_return', models.FloatField(verbose_name='日收益率')),
            ],
            options={
                'verbose_name': '回测权益',
                'verbose_name_plural': '回测权益',
                'db_table': 'backtest_equity',
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='交易类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='手续费')),
                ('datetime', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '回测交易',
                'verbose_name_plural': '回测交易',
                'db_table': 'backtest_trades',
                'ordering': ['datetime'],
            },
        ),
    ]
