# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy'),
        ),
    ]
