# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtesting', '0002_initial'),
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtestequity',
            name='backtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_curve', to='backtesting.backtest'),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='backtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtest'),
        ),
        migrations.AddField(
            model_name='backtesttrade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.stock'),
        ),
        migrations.AddIndex(
            model_name='backtestequity',
            index=models.Index(fields=['date'], name='backtest_eq_date_c8d1c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backtestequity',
            unique_together={('backtest', 'date')},
        ),
    ]
