# Generated by Django 6.0.3 on 2026-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组合名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总资金')),
                ('available_cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='可用资金')),
                ('frozen_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='冻结资金')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '投资组合',
                'verbose_name_plural': '投资组合',
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='配置名称')),
                ('target_percent', models.FloatField(default=0, verbose_name='目标比例')),
                ('current_percent', models.FloatField(default=0, verbose_name='当前比例')),
            ],
            options={
                'verbose_name': '资产配置',
                'verbose_name_plural': '资产配置',
                'db_table': 'portfolio_allocation',
            },
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总市值')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='现金')),
                ('positions_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='持仓市值')),
                ('daily_return', models.FloatField(default=0, verbose_name='日收益率')),
            ],
            options={
                'verbose_name': '组合历史',
                'verbose_name_plural': '组合历史',
                'db_table': 'portfolio_history',
            },
        ),
    ]
