# Generated by Django 6.0.3 on 2026-03-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioallocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='portfolio.portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfoliohistory',
            index=models.Index(fields=['date'], name='portfolio_h_date_d10858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliohistory',
            unique_together={('portfolio', 'date')},
        ),
    ]
